### DISCUSSION TITLE
Change port 80

### DISCUSSION THREAD

**Discussion by fab135** [dunglas/symfony-docker#165] [General]
Hello,

I would like to change port of container.

I tried to change in docker-compose, in caddyfile... but I'm always redirect to **https :80** or I get a blank page on my specific port if I disable redirect instruction on Caddy.

For example I would like to run **localhost:9595**.

Thanks.

**Comment by maxhelias** [comment]
You just need to change the port configuration of the caddy service in the docker-compose

**Reply by fab135** [reply]
Just that ? :

```
ports:
      # HTTP
      - target: 80
        published: 80 => to 9595 ??
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp 
```
