### DISCUSSION TITLE
Disabling apcu and opcache for local development?

### DISCUSSION THREAD

**Discussion by freiondrej-lmc** [dunglas/symfony-docker#237] [Q&A] [answered]
Hello,
I'm using symfony-docker to simplify my local development (great job, it's amazing!).
I mounted the work dir into the php container as a volume `- .:/srv/app`, but the changes I did to my local files did not take effect when running php. I tried adding `opcache_reset()` and `apcu_clear_cache()` to public/index.php, but it did not help. Then I tried disabling opcache and apcu by commenting out the Dockerfile part with `docker-php-ext-enable apcu opcache;` and it indeed solved the problem. However doing it like this felt a bit cumbersome and made me think I'm probably doing something wrong, but I did not find anything about this in the README nor the docs/. What is the best way to do this? 

Thank you! 🙂

**Comment by florentdrousset** [comment]
Thanks a lot for this, I couldn't understand why the code was updating in the container but the changes were not reflected in the browser. I don't if there's another way to disable the cache though.

**Comment by cizordj** [comment, marked as answer]
You can try disabling the opcache via environment variables or via **php-ini-overrides.ini**. Try putting this into your docker-compose file, in the PHP section:
```yaml
environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
      PHP_OPCACHE_PRELOAD: ""
```
Or if you prefer the ini method:
**php-ini-overrides.ini**
```ini
opcache.enable=0
```
**docker-compose.yaml**
```yaml
  php:
    volumes:
      - ./path-to-your/config-directory/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
```
This should not affect your production setup.
