### DISCUSSION TITLE
Maker bundle docker extension

### DISCUSSION THREAD

**Discussion by Nayte91** [dunglas/symfony-docker#262] [Ideas]
Hi there,

So I don't know if there is any value into this but I was thinking that some make:system:xxxx commands are a good way for this "component" to be used,

- scripts can identify databases info,
- if a mercure container is needed,
- best practices for webserver,
- suggest optimized php.ini conf for a symfony app,
- and so on because it's a service and it has access to config, env, vendor, can ask questions to the user about what he needs, ...

How are we willing to need containers ?
1. When a project already exists and already have php available : make command is sexier than [copy pasting skeleton](https://github.com/dunglas/symfony-docker/blob/main/docs/existing-project.md) ?
2. When a project doesn't exists or php is not avaiable : can we ship some kind of container.sh solo file that will just lauch a good php/composer container that will allows to use make: commands (existing one) or create-project ?

How the container system/project folders will be structured ?
- Condom pattern : your foo/ folder has compose.yml and system/, and a app/ folder where the symfony project belongs,
- Bubblegum pattern : your foo/ folder is your symfony project, where compose.yml and system/ belongs at the root lvl,
- Umbrella pattern : your foo/ folder contains compose.yml and system/, and your project/ folder is at the same level than foo/.

We can ask the user for thoses.

My point is : we can improve drastically usability of containers (I try to avoid naming "docker" for agnostic purposes) by programmatically creating system containers with a maker bundle, than just this (very good) static repository.

I'm a bit poor/noobish dev, but I'm quite specialized in Symfony and Docker for my little dev experience so if we can discuss about this, if I can help on any way..

WDYT ?

**Comment by Nayte91** [comment]
ty-pi-cal : I was searching for days if anything already exists around, and few minutes after posting, I saw my bin/console offering me " make:docker:database". I swear I looked here before! 

After testing, I see that the command doesn't take the already existing informations in the common DATABASE_URL env variable;

On my side, what I usually do to make things "a bit more dynamic", is splitting DATABASE_URL into :

```
DATABASE_DRIVER=pdo_pgsql
DATABASE_VERSION=14
DATABASE_CHARSET=utf8
DATABASE_HOST=database
DATABASE_PORT=5432
DATABASE_NAME=test
DATABASE_SCHEMA=public
DATABASE_USER=root
DATABASE_PASSWORD=ChangeMe
```

Therefore I can deduct some information for my docker-compose.yml : 

```
database:
    image: postgres:${DATABASE_VERSION:-latest}-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER:-main}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-main}
      POSTGRES_DB: ${DATABASE_NAME:-main}
    ports:
      - target: ${DATABASE_PORT:-5432}
        published: ${DATABASE_PORT:-5432}
```

Maybe we can deduct the DB engine from the driver? Or is there any other way to get those informations and inject them dynamically in docker-compose.yml, but keeping DATABASE_URL variable?

Also adding a make:docker:backend and make:docker:server can be a thing?

Fun fact: [specifications were updated](https://docs.docker.com/compose/compose-file/) for docker compose and
- for OCI's agnostic purposes, docker-compose.yml renamed to compose.yaml
- version is no longer a thing (yay!)
- and few other minor things for me, but take a look.

So many ideas, so many discussions, so many cool stuff to do. I'll continue monologing here later :)

**Reply by mario-fehr** [reply]
something like this 
`DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=${MYSQL_VERSION}`

**Reply by Nayte91** [reply]
Thank you, but in which way ? The value of keeping DATABASE_URL variable is to make it the universal source of info, to feed:
- docker-compose
- doctrine config

But if you use this kind of variable in DATABASE_URL, then where is the source? if the sources are the bunch of variables DATABASE_THINGS, then why not using them?
And, is it possible to use those ${variables} in the .env file? I didn't knew that!

**Reply by mario-fehr** [reply]
I use a custom docker setup and not symfony-docker, but you can tell every dock container in `docker-compose.yml` what .env files it should be considering to use 

```
mysql:
        image: 'mysql:${MYSQL_VERSION}'
        restart: 'unless-stopped'
        env_file:
            - '.env.mysql'
            - '.env.mysql.local'
        volumes:
            - 'mysql-data:/var/lib/mysql:rw'
        networks:
            - 'backend'
        ports:
            - '127.0.0.1:3306:3306'

```
And the symfony `.env` files can use these infos as well. I hope I could help you a bit. If you have more questions, feel free to ask.
