### DISCUSSION TITLE
set prod to environment and the .env.local.php

### DISCUSSION THREAD

**Discussion by ziat1988** [dunglas/symfony-docker#405] [General]
In order to see the app in prod mode, I do this in docker-compose.prod.yml;
```yaml
services:
  php:
    environment:
      APP_SECRET: ChangeMe
      APP_ENV : prod
      SERVER_NAME: localhost
```
Then I run `docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d`. It works and I can see I'm in production mode with `php bin/console about`.

Then, back in the .env, I see the instruction state that  Run "composer dump-env prod" to compile .env files for production use. 
So my question is : what is the way to set the production mode for deploy? Should I just have any variable in docker.compose.prod.yml or I should run  composer dump-env prod to generate .env.local.php and have the variables in that file? I'm really confusing about the environment with docker and .env file.
