### DISCUSSION TITLE
Accessing Mysql database inside the container

### DISCUSSION THREAD

**Discussion by creativehubspace** [dunglas/symfony-docker#592] [Q&A]
When I try to `docker exec -it mysql-container mysql -uapp -p` , I keep getting `Access denied for user 'app'@'localhost' (using password: YES) .` What am I missing? 
Running` docker compose exec php bin/console dbal:run-sql -q "SELECT 1" && echo "OK" || echo "Connection is not working"`  does echo "OK", so the database connection is working as expected.

**Comment by Tovintsoa** [comment]
I have the same problem.

**Comment by TacticsJan** [comment]
I'm also facing the same issue with a psql database. My php container is connecting to it all fine but I am unable to connect to the db as a data source in PHPStorm or unable to connect to it from the database container.

**Reply by david-bertran** [reply]
old topic but had a similar issue and solved it by binding the ports on the compose.yaml 
``` 
 database:
    image: mysql:${MYSQL_VERSION:-8}
    platform: linux/amd64/v8
    ports:
      - '3306:3306'
```
