### DISCUSSION TITLE
GitHub Actions can't execute bin/console command

### DISCUSSION THREAD

**Discussion by clussiana** [dunglas/symfony-docker#599] [Q&A] [answered]
Hello,

I encountered an issue while trying to run CI on GitHub Actions and received the following error message: `OCI runtime exec failed: exec failed: unable to start container process: exec: "bin/console": permission denied: unknown`

To resolve this issue, I implemented the following instruction in the CI configuration:
```yaml
      -
        name: Make executable
        run: chmod +x bin/console
```
However, since I'm relatively new to Docker and GitHub Actions, I'm not entirely sure if this is the optimal solution. Any feedback or alternative suggestions would be greatly appreciated.

Thank you!
