### ISSUE TITLE
Add yarn/npm

### ISSUE THREAD

**Issue by fherbin** [dunglas/symfony-docker#129]
everything is in the title
can you add yarn to the php container?

**Comment by dunglas** [comment]
It's not a good idea in production.  We need to find a way to have them in dev but not in prod.

**Comment by fherbin** [comment]
and for

**Comment by BaptisteCrouzet** [comment]
> It's not a good idea in production. We need to find a way to have them in dev but not in prod.

Why it is not a good idea in production ? Is it for build time reasons ?

**Comment by dunglas** [comment]
Mostly for security reasons. You don't want something useless in prod in your images.

**Comment by fherbin** [comment]
maybe a little off topic but, isn't it a good practice that services in containers are not executed as root ?

**Comment by Julien-Broyard** [comment]
You could create a docker-compose.dev.yml and add the node.js image with yarn there. 

Then you could run this command.

```shell
docker-compose up -f docker-compose.yml -f docker-compose.dev.yml
```

How is it ?

**Comment by torbenbr** [comment]
You can add this in your Dockerfile

before php stage
```
ARG NODE_VERSION=14

# node "stage"
FROM node:${NODE_VERSION}-alpine AS symfony_assets_builder

WORKDIR /srv/app

RUN mkdir public

COPY package.json yarn.lock ./

RUN yarn install

COPY assets assets/
COPY webpack.config.js ./

RUN yarn build
```

And this in the php stage
```
COPY --from=symfony_assets_builder /srv/app/public/build public/build
```

**Comment by abdounikarim** [comment]
Hello, can we use something like this in the `docker-compose.override.yaml` file ? 

```yaml
encore:
        command: ["yarn", "dev-server", "--host=0.0.0.0"]
        container_name: encore
        image: node:10-alpine
        ports:
            - "${DEV_SERVER_PORT:-8080}:8080"
        volumes:
            - .:/srv/app
```

And use this command to generate assets : 
```console
docker-compose run encore yarn --cwd /srv/app watch
```

With the current configuration, this will be used only in dev right ?
