### ISSUE TITLE
Adding symfony-docker on existing project

### ISSUE THREAD

**Issue by HamHamFonFon** [dunglas/symfony-docker#177]
Hi,
I'm trying to add this docker stack on my existing project, following https://github.com/dunglas/symfony-docker/blob/main/docs/existing-project.md . I'm using PHP 7.4, not 8.0 yet. I'm using only PHP image and container from this repo; nginx, DB, elasticsearch etc are from my previous docker stack. Also i'm not admin on my laptop and i don't have composer, npm and yarn installed on it (i want to use php and composer commands in the container).

In dockerfile, i've removed command "create-project" and i've got error on : 
```
RUN set -eux; \
	# mkdir -p var/cache var/log; \
	# composer install --prefer-dist --no-dev --no-progress --no-scripts --no-interaction; \
	composer dump-autoload --classmap-authoritative --no-dev; \
	# composer symfony:dump-env prod; \
	#composer run-script --no-dev post-install-cmd; \
	chmod +x bin/console; sync
```
Error : 
```
+ composer dump-autoload --classmap-authoritative
Composer could not find a composer.json file in /srv/app
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage
The command '/bin/sh -c set -eux; 	composer dump-autoload --classmap-authoritative ; 	chmod +x bin/console; sync' returned a non-zero code: 1
ERROR: Service 'php' failed to build
```
It looks like my project is not mounted on /srv/app. 
If all compose command are commented, got error on chmod command: 

```
Step 14/23 : RUN set -eux; 	chmod +x bin/console; sync
 ---> Running in c468dab6c9a5
+ chmod +x bin/console
chmod: bin/console: No such file or directory
The command '/bin/sh -c set -eux; 	chmod +x bin/console; sync' returned a non-zero code: 1
ERROR: Service 'php' failed to build
```

In docker-compose.yml :
```
  php:
    build:
      context: docker/php7-fpm
      target: symfony_php
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    container_name: dso_php
    hostname: php
    volumes:
      - ./:/srv/app:rw,cached
      - ./docker/php7-fpm/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      - "$SSH_AUTH_SOCK:/ssh-agent:ro"
    env_file:
      - ".env"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - TERM=xterm-color
    links:
      - mail
    networks:
      - dso_stack
``` 

Full docker-compose : https://github.com/HamHamFonFon/deep-space-objects/blob/refactoring-docker-stack/docker-compose.yml
Full DockerFile : https://github.com/HamHamFonFon/deep-space-objects/blob/refactoring-docker-stack/docker/php7-fpm/Dockerfile

Thanks :)
