### ISSUE TITLE
Move Dockerfile to docker folder

### ISSUE THREAD

**Issue by GErpeldinger** [dunglas/symfony-docker#203]
Hello,

I propose to move the Dockerfile in the docker folder, I think it is interesting to keep a minimum of file in the root of the project.
This is easily possible by adding the `dockerfile` option in the build of the docker-compose.

example

```yaml
# docker-compose.yml
services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: symfony_php

# ...

  caddy:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: symfony_caddy
```

What do you think about it?
