### ISSUE TITLE
Consume Messenger message

### ISSUE THREAD

**Issue by Romaixn** [dunglas/symfony-docker#205]
Hello ! What is the "right" way to consume messages in dev + production? (Symfony Messenger)

Using `supervisor` like describe in [documentation](https://symfony.com/doc/current/messenger.html#supervisor-configuration) ?
How to set it up properly?

Thanks for your help

**Comment by dunglas** [comment]
It's not necessary to use supervisor when using Docker Compose or an orchestor. Adding a new worker service and configuring it to restart automatically when it stops is enough. With Docker Compose, you can use the `restart-policy` directive.

**Comment by Romaixn** [comment]
Thanks for your reply !

I tried to do a service but it failed : 
```
SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed:   
messenger_1  |   Connection refused                                                           
messenger_1  |          Is the server running on that host and accepting TCP/IP connections?
```

I add this in `docker-compose.yaml`
```
 messenger:
    build:
      context: .
      target: symfony_messenger
    command: 'sh -c "php bin/console messenger:consume async"'
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      - php
```

And this in Dockerfile : 
```
FROM symfony_php AS symfony_messenger
WORKDIR /srv/app/

ENTRYPOINT ["docker-entrypoint"]
```

**Comment by SanderVerkuil** [comment]
The hostname is not `127.0.0.1` but the name of the docker container as specified in the `docker-compose.yml`. So if you change the config from `127.0.0.1` to `php`, or `caddy`, or where the mercure hub is running, it should work.

**Comment by aelfannir** [comment]
> Thanks for your reply !
> 
> I tried to do a service but it failed :
> 
> ```
> SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed:   
> messenger_1  |   Connection refused                                                           
> messenger_1  |          Is the server running on that host and accepting TCP/IP connections?
> ```
> 
> I add this in `docker-compose.yaml`
> 
> ```
>  messenger:
>     build:
>       context: .
>       target: symfony_messenger
>     command: 'sh -c "php bin/console messenger:consume async"'
>     healthcheck:
>       interval: 10s
>       timeout: 3s
>       retries: 3
>       start_period: 30s
>     restart: unless-stopped
>     depends_on:
>       - php
> ```
> 
> And this in Dockerfile :
> 
> ```
> FROM symfony_php AS symfony_messenger
> WORKDIR /srv/app/
> 
> ENTRYPOINT ["docker-entrypoint"]
> ```

This worked for me, i added DATABASE_URL environment variable

```yaml

  messenger:
    build:
      context: .
      target: app_messenger
    command: 'sh -c "php bin/console messenger:consume async"'
    environment:
        DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      - php

```

I used `database` instead of `127.0.0.1`
.env
```yaml
DATABASE_URL=postgresql://symfony:ChangeMe@database:5432/app?serverVersion=14&charset=utf8
```

Not sure is it's the right way but it worked
