### ISSUE TITLE
App unreachable when running docker image

### ISSUE THREAD

**Issue by ugo-fl** [dunglas/symfony-docker#234]
(Far from being a Docker expert here, so it could be just a newbie issue)

For CI/CD purpose, I'm trying to build an image of my app using Bitbucket pipeline so here's basically what I do: 

```
pipelines:
  default:
    - step:
        name: "Docker push image"
        script:
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build -t my/repo:${BITBUCKET_COMMIT::7} .
          - docker push my/repo:${BITBUCKET_COMMIT::7}
        services:
          - docker
```

This works fine, but then when I run my image like so :

`docker run -p 80:80/tcp -p 443:443/tcp -p 443:443/udp my/repo:XXXXXX`

The app is unreachable :

![image](https://user-images.githubusercontent.com/1921477/160781428-39bec771-a263-46a7-b9ed-40a371fa5f8d.png)
