### ISSUE TITLE
Autowire of repositories not working properly

### ISSUE THREAD

**Issue by Gonzalo1987** [dunglas/symfony-docker#241]
Hello, 
I'm trying to dockerize a `Symfony 5.4` project that is currently working on, after follow the instructions here indicated: https://github.com/dunglas/symfony-docker/blob/main/docs/existing-project.md

and after build my dockerfile, I've get that my php container is rebooting randomly
This is probably caused, for some problem regarding the autowired services. 

The folder 'App\Repository' seems not be autowired, that cause the container exit with code 1 trying to make the cache:clear. That folder should be autowired because the service.yaml config: 

```
services: 
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
```

This project and configuration is working nicely with in local machine (w10) and in the prod server (centos) using php 8.0 with apache. 

Moreover the other services of the project seems to be autowired perfectly, but I can't make this container work for this problem.

Any advice?
