### ISSUE TITLE
Slow on windows

### ISSUE THREAD

**Issue by Vandersteen** [dunglas/symfony-docker#242]
A fresh install on windows with wsl2 gives me around 5-6 seconds for every call I make.

Do you have any suggestions on how to improve the performance on windows ?

I believe it to be IO issues but i'm not sure

**Comment by stefanpoensgen** [comment]
I'm using wsl/wsl2 approx two years now and never experinced such an issue.
I would try to exclude wsl2 from windows defender realtime protection and if you use other protection software, go back to windows defender.

**Comment by Ezar101** [comment]
@Vandersteen 

> To get the best out of the file system performance when bind-mounting files, we recommend storing source code and other data that is bind-mounted into Linux containers (i.e., with docker run -v <host-path>:<container-path>) in the Linux file system, rather than the Windows file system. You can also refer to the [recommendation](https://docs.microsoft.com/en-us/windows/wsl/compare-versions) from Microsoft.

[https://docs.docker.com/desktop/windows/wsl/#best-practices](https://docs.docker.com/desktop/windows/wsl/#best-practices)

**Comment by aelfannir** [comment]
I was facing the same issue, enabled wsl2/disabled real-time protection didn't help

I've found that `vendor` and  `var` folders are affecting the performance

*docker-compose.yml*
```yml
...
services:
  php:
      ...
      volumes:
        - php_socket:/var/run/php
        - vendor:/srv/app/vendor
        - var:/srv/app/AE-API/var
        
volumes:
  ...
  vendor:
  var:
```
