### ISSUE TITLE
[Docs] Explain how to disable apcu and opcache in development

### ISSUE THREAD

**Issue by freiondrej-lmc** [dunglas/symfony-docker#245]
Something like this:

You can try disabling the opcache via environment variables or via **php-ini-overrides.ini**. Try putting this into your docker-compose file, in the PHP section:
```yaml
environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
      PHP_OPCACHE_PRELOAD: ""
```
Or if you prefer the ini method:
**php-ini-overrides.ini**
```ini
opcache.enable=0
```
**docker-compose.yaml**
```yaml
  php:
    volumes:
      - ./path-to-your/config-directory/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
```
This should not affect your production setup.

_Originally posted by @cizordj in https://github.com/dunglas/symfony-docker/discussions/237#discussioncomment-2673781_
