### ISSUE TITLE
Handle user file upload

### ISSUE THREAD

**Issue by tdumalin** [dunglas/symfony-docker#374]
Hi there,

This is not a bug report but there is no documentation about how to handle user file uploads in production.

I use [VichUploaderBundle]( https://github.com/dustin10/VichUploaderBundle) to handle files uploaded by user.
So basically all the uploaded files are stored in `public/uploads` directory. 

I updated my php docker-entry-point.sh

```sh
#docker/php/docker-entrypoint.sh

#existing acl
setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX var
setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX var

# add acl on uploads
setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX public/uploads
setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX public/uploads
```

In dev there is no problem because php and caddy services both have a volume to bind the public folder.

But in production there is no bind between those folder. How should I do ?

Thanks for the help,

**Comment by maxhelias** [comment]
Hi,
You should not upload your files to the `public/uploads` folder of your container in production. 
Containers are ephemeral by nature. Any data that should outlive the container should be in a volume or third party (like S3)

**Comment by tdumalin** [comment]
@maxhelias,

Thanks for your answer, so if i want to use volume it should be shared between caddy and php (caddy to render to the end user/php for writting)?
It's this configuration seems ok to you:

```yaml
#docker-compose.prod.yml
version: "3.4"

# Production environment override
services:
    php:
        volumes:
            - uploads:/srv/app/public/uploads

    caddy:
        volumes:
            - uploads:/srv/app/public/uploads

volumes:
    uploads:
```
What do you think about adding a file in the doc folder about how to handle user uploaded files ?
