### ISSUE TITLE
test and dev environment variables with docker-compose

### ISSUE THREAD

**Issue by grambas** [dunglas/symfony-docker#381]
we can use docker compose environment element to define symfony envs. For example DATABASE_URL.

```
services:
  php:
    environment:
      DATABASE_URL:  "mysql..."
```
Using this method all `.env` files, even .`env.test.local` file will be overwritten. In that case my tests runs on DATABASE_URL which is defined in docker-compose what is wrong, becouse test env has another database connection. My question is if it is possible to define symfony envs with docker-compsose for both dev and test environment
