### ISSUE TITLE
How to make files editable ? 

### ISSUE THREAD

**Issue by grekpg** [dunglas/symfony-docker#416]
All files are created as root so src/ , config/ is read only ... 

I understand
`docker compose run --rm php chown -R $(id -u):$(id -g) .
`
temporary fix permission, but i have own verdors - composer install create files as root. 
Is possible to fix it pernamently ?

**Comment by AlexandreGerault** [comment]
I think you can add a `user` key to the `php` binding your own user id and group id, like this for example:

```yaml
services:
  php:
    build:
      context: .
      target: app_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://caddy/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    user: 1000:1000
```
