### ISSUE TITLE
Is there any way to disable completely HTTPS ? 

### ISSUE THREAD

**Issue by SirMishaa** [dunglas/symfony-docker#451]
Hello, 

For some specific reason, I'd like to disable completely HTTPS. We're already using some kind of proxy, and we do not want HTTPS on Caddy / application side. 

Is there a way to disable it ?

**Comment by maxhelias** [comment]
Hello,

Yes, you can use the environment variable `CADDY_EXTRA_CONFIG` declared here https://github.com/dunglas/symfony-docker/blob/main/docker/caddy/Caddyfile#L8 to add any option.

You should declare it in the yaml file, something like this : 
```
version: "3.4"
services:
  ...
  caddy:
    environment:
      CADDY_EXTRA_CONFIG: "${CADDY_EXTRA_CONFIG}"
```
Start it with the variable and the right file.
```
CADDY_EXTRA_CONFIG="auto_https off" \
docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
```
Or you can directly pass the option in the yaml file.

And you find here the caddy option about auto https : https://caddyserver.com/docs/caddyfile/options#auto-https
