### ISSUE TITLE
Ability to extend Docker PHP service

### ISSUE THREAD

**Issue by lermontex** [dunglas/symfony-docker#467]
After the PR #460 merge there is no longer an option to extend the core PHP service, but what if it is necessary?

For example, I'm using Docker Swarm and I need a separate service for Crontab/Messenger. Previously I could extend the base PHP service, but now it comes bundled with FrankenPHP

What if the service doesn't require a web server? Previously, it was possible to use a PHP service as a base for other services, a simple example:

Dockerfile:
```
...
FROM php_prod AS crontab_prod

COPY --link docker/crontab/crontabs /etc/crontabs/root

CMD ["crond", "-f"]
```

docker-compose.yml
```
services:
  php:
    build:
      context: .
      target: php_prod
    volumes:
      - php_socket:/var/run/php
      - php_data:/srv/app/data:rw

  caddy:
    build:
      context: .
      target: caddy_prod
    depends_on:
      php:
        condition: service_healthy
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config

  crontab:
    build:
      context: .
      target: crontab_prod
    depends_on:
      php:
        condition: service_healthy
    volumes:
      - php_data:/srv/app/data:rw

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  php_data:
```

Thus, all services had PHP with the same settings. As you can see, PR #460 limits the possibility of flexible configuration, because every service will now have a FrankenPHP web server even if it is not needed, which is sad.
