### ISSUE TITLE
Best way to install yarn and nodejs

### ISSUE THREAD

**Issue by Jenny13800** [dunglas/symfony-docker#497]
Hi !

Thank you for this great job! It's really great.

I want to install nodejs and yarn in docker.
What's the best way to do it ?
It would be great to have symfony/webpack-encore-bundle in Extra Services.

There is an [issue](https://github.com/dunglas/symfony-docker/issues/372) on this topic but i don't know if it's the right method. The dockerfile is different.

Thank you for your help.

**Comment by zpi12lmm** [comment]
I can offer my version, how I implemented it in my project. Since we only need nodejs to minify and package assets, we don't need to create a separate service in production mode, so let's add a service for developer mode, for this, add the following service to the `compose.override.yaml` file:
```
services:
  node:
    image: node:lts-alpine
    tty: true
    working_dir: /app
    depends_on:
      - php
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
``` 
After that, run your docker compose and you will have a new `node` service in developer mode, and by going into the `docker compose exec node sh` container, you can run all the commands you need for symfony/webpack-encore-bundle.

By the way, to deploy assets in production mode, you can use the `scp` command to transfer already compiled files, or on the production server itself, before starting the docker compose, build as follows:
```
docker run --rm -v ./:/app -w /app node:lts-alpine sh -c 'yarn install; yarn build' && rm -rf './node_modules/'
```
