### ISSUE TITLE
Prod deploy not work

### ISSUE THREAD

**Issue by treeindark** [dunglas/symfony-docker#521]
Hello,
docker with project in dev work,

But in prod 
`docker compose -f compose.yaml -f compose.prod.yaml    up --wait`

folder project (in container) is not my project's files, composer.json is for initial project not mine and src/Controller/defaultController only...

what i made wrong????

**Comment by dunglas** [comment]
Can you try to disable the worker mode?

**Comment by maxhelias** [comment]
I've added a note on how to do it here : https://github.com/dunglas/symfony-docker/pull/518

**Comment by aelfannir** [comment]
> Can you try to disable the worker mode?

I faced the same issue, production build contains empty project even the worker is disabled.

Here's my compose.prod.yaml

```yaml
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      FRANKENPHP_CONFIG: 
```
