### ISSUE TITLE
Production Build Issue: Empty Project

### ISSUE THREAD

**Issue by aelfannir** [dunglas/symfony-docker#573]
* Encountering an empty project in the production build despite attempts to resolve. Tried disabling worker mode, but the issue persists. Relevant details in the https://github.com/dunglas/symfony-docker/issues/521

here's compose.prod.yaml

```yaml
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      FRANKENPHP_CONFIG: 
```
