### ISSUE TITLE
Confusion with Mailer Port Mapping in docker-compose.override.yaml

### ISSUE THREAD

**Issue by bedfir** [dunglas/symfony-docker#600]
**Issue Description:**

When installing the Mailer, the recipe modifies the `docker-compose.override.yaml` file by adding the following service:

```yml
###> symfony/mailer ###
mailer:
  image: axllent/mailpit
  ports:
    - "1025"
    - "8025"
  environment:
    MP_SMTP_AUTH_ACCEPT_ANY: 1
    MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
```

However, this can lead to confusion as the ports mapping might not match the expected behavior.

**Expected Behavior:**

The `docker-compose.override.yaml` file should adhere to the default ports defined by Mailpit to ensure consistency and clarity.

**Actual Behavior:**

When running docker ps, the ports mapping for the Mailer container (mailer-1) shows:
`4840d11c6714   axllent/mailpit   "/mailpit"   6 minutes ago   Up 6 minutes   1110/tcp, 0.0.0.0:32789->1025/tcp, :::32789->1025/tcp, 0.0.0.0:32788->8025/tcp, :::32788->8025/tcp   mailer-1`

And when checking the logs inside the Mailer container using `docker logs mailer-1`, it indicates:
```bash
time="2024/04/07 21:18:52" level=info msg="[smtpd] enabling any authentication (insecure)"

time="2024/04/07 21:18:52" level=info msg="[smtpd] starting on [::]:1025 (no encryption)"

time="2024/04/07 21:18:52" level=info msg="[http] starting on [::]:8025"

time="2024/04/07 21:18:52" level=info msg="[http] accessible via http://localhost:8025/"
```
The logs indicate that the service is accessible via port 8025, which contradicts the port mapping specified in the `docker-compose.override.yaml file.`

Please make sure to adjust the port mappings in the `docker-compose.override.yaml` file to match the default ports defined by [Mailpit ](https://mailpit.axllent.org/docs/install/docker/)for a smoother and more consistent setup experience.
