### ISSUE TITLE
Could not connect to /var/run/php/php-fpm.sock at build time

### ISSUE THREAD

**Issue by astronati** [dunglas/symfony-docker#605]
Hi,

during the build of your previous template, sometimes it happens that following errors comes out:

`Could not connect to /var/run/php/php8.2-fpm.sock.`

Any idea?

**Comment by maxhelias** [comment]
Hi,

Try this : https://github.com/dunglas/symfony-docker/issues/289#issuecomment-1267554124

**Comment by astronati** [comment]
Hi @maxhelias thanks for your comment.

It seems it is not working. Just let me share with you what I have in my `ci.yaml`:

```
name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: Dockerfile
          ignore: DL3007,DL3018 # Ignore using latest on mlocati/php-extension-installer & version in apk add

  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
        with:
          memory_limit: -1
          php_extensions: intl zip gd

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/ tests/
          php_extensions: intl zip gd

  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker compose down --remove-orphans
#      - name: Pull images
#        run: docker compose pull
      - name: Build images
        run: docker compose build --pull --no-cache
      - name: Start services
        run: docker compose up -d
      - name: Wait for services
        run: |
          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker compose ps -q php)")"; do
            case $status in
              starting)
                echo 'starting'
                docker inspect --format "{{json .State.Health }}" $(docker-compose ps -q php) | jq
                sleep 1;;
              healthy)
                echo 'healthy'
                docker inspect --format "{{json .State.Health }}" $(docker-compose ps -q php) | jq
                exit 0;;
              unhealthy)
                echo 'unhealthy'
                docker inspect --format "{{json .State.Health }}" $(docker-compose ps -q php) | jq
                exit 1;;
            esac
          done
          echo 'result?'
          docker inspect --format "{{json .State.Health }}" $(docker-compose ps -q php) | jq
          exit 1
      - name: Check HTTP reachability
        run: curl http://localhost
      - name: Check HTTPS reachability
        run: curl -k https://localhost

```

It is failing in the "Wait for services" section and the log says:

```
starting
{
  "Status": "starting",
  "FailingStreak": 0,
  "Log": [
    {
      "Start": "2024-04-16T09:55:07.137105375Z",
      "End": "2024-04-16T09:55:07.31[49](https://github.com/castiglioni-srl/castiglioni/actions/runs/8703362645/job/23869366453?pr=578#step:6:50)97017Z",
      "ExitCode": 1,
      "Output": "Could not connect to /var/run/php/php-fpm.sock\n"
    }
  ]
}
```

Any thoughts?
