### ISSUE TITLE
.env.prod.local not picked up on docker compose up

### ISSUE THREAD

**Issue by fleonardelli** [dunglas/symfony-docker#628]
In the docs https://github.com/dunglas/symfony-docker/blob/main/docs/production.md there last section says that you can pass env variables adding the .env.prod.local env_file to compose.prod.yaml. 

I've added it, and created .env.prod.local:
```
SERVER_NAME=your-domain-name.example.com
APP_SECRET=ChangeMe
CADDY_MERCURE_JWT_SECRET=ChangeThisMercureHubJWTSecretKey
```

So now instead of running:
```
SERVER_NAME=your-domain-name.example.com \
APP_SECRET=ChangeMe \
CADDY_MERCURE_JWT_SECRET=ChangeThisMercureHubJWTSecretKey \
docker compose -f compose.yaml -f compose.prod.yaml up -d --wait
```

I want to run
`docker compose -f compose.yaml -f compose.prod.yaml up -d --wait
`

But I keep getting: 
WARN[0000] The "CADDY_MERCURE_JWT_SECRET" variable is not set. Defaulting to a blank string.
WARN[0000] The "CADDY_MERCURE_JWT_SECRET" variable is not set. Defaulting to a blank string.

If I run it 
`CADDY_MERCURE_JWT_SECRET=ChangeThisMercureHubJWTSecretKey docker compose -f compose.yaml -f compose.prod.yaml up -d --wait`

The container stops restarting, but if I run 
`export`
within the container, I can see the SERVER_NAME is the one from the .env variable and not from the .env.prod.local

I can't figure out how to make it pick up .env.prod.local.

**Comment by 7-zete-7** [comment]
Hello @fleonardelli!

You can say to Docker Compose to use non-default _.env_-file by setting `--env-file` option or by using the `env_file` attribute in (one of) _compose.yaml_ file (see https://docs.docker.com/compose/environment-variables/set-environment-variables/).

**Comment by maxhelias** [comment]
Can you provide a reproducer pls ?

**Comment by fleonardelli** [comment]
Run: `git clone https://github.com/dunglas/symfony-docker.git .`

Modify the compose.prod.yaml to:

```
# Production environment override
services:
  php:
    env_file:
      - .env.prod.local
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
```

Add .env.prod.local:
```
SERVER_NAME=:80
APP_SECRET=ChangeMe
CADDY_MERCURE_JWT_SECRET=ChangeThisMercureHubJWTSecretKey
```

Now run: `docker compose -f compose.yaml -f compose.prod.yaml up -d --wait`

It will output:
WARN[0000] The "APP_SECRET" variable is not set. Defaulting to a blank string.
WARN[0000] The "CADDY_MERCURE_JWT_SECRET" variable is not set. Defaulting to a blank string.
WARN[0000] The "CADDY_MERCURE_JWT_SECRET" variable is not set. Defaulting to a blank string.
[+] Running 0/1

@maxhelias I guess it's enough. Because of that if I request the server it will always print phpinfo() output.
