### ISSUE TITLE
Unable to deploy in production

### ISSUE THREAD

**Issue by Stoufiler** [dunglas/symfony-docker#629]
Hello, I'm trying to deploy my symfony project in production using github actions and symfony-docker

After running  `docker compose -f compose.yaml -f compose.prod.yaml up -d --wait --force-recreate` when I look for logs it seems that symfony is creating a new application instead of using the one in the folder :

```
Attaching to database-1, php-1
database-1  |
database-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
database-1  |
database-1  | 2024-05-08 02:09:39.795 UTC [1] LOG:  starting PostgreSQL 16.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
database-1  | 2024-05-08 02:09:39.795 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database-1  | 2024-05-08 02:09:39.795 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database-1  | 2024-05-08 02:09:39.798 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database-1  | 2024-05-08 02:09:39.805 UTC [24] LOG:  database system was shut down at 2024-05-08 02:09:32 UTC
database-1  | 2024-05-08 02:09:39.811 UTC [1] LOG:  database system is ready to accept connections
php-1       | Creating a "symfony/skeleton " project at "./tmp"
php-1       | Installing symfony/skeleton (v7.0.99)
php-1       |   - Downloading symfony/skeleton (v7.0.99)
php-1       |   - Installing symfony/skeleton (v7.0.99): Extracting archive
php-1       | Created project in /app/tmp
php-1       | /app
php-1       | ./composer.json has been updated
php-1       | Running composer update php runtime/frankenphp-symfony
php-1       | Loading composer repositories with package information
php-1       | Updating dependencies
php-1       | Lock file operations: 18 installs, 0 updates, 0 removals
php-1       |   - Locking psr/container (2.0.2)
php-1       |   - Locking psr/event-dispatcher (1.0.0)
php-1       |   - Locking psr/log (3.0.0)
php-1       |   - Locking runtime/frankenphp-symfony (0.2.0)
php-1       |   - Locking symfony/dependency-injection (v7.0.7)
php-1       |   - Locking symfony/deprecation-contracts (v3.5.0)
php-1       |   - Locking symfony/error-handler (v7.0.7)
php-1       |   - Locking symfony/event-dispatcher (v7.0.7)
php-1       |   - Locking symfony/event-dispatcher-contracts (v3.5.0)
php-1       |   - Locking symfony/flex (v2.4.5)
php-1       |   - Locking symfony/http-foundation (v7.0.7)
php-1       |   - Locking symfony/http-kernel (v7.0.7)
php-1       |   - Locking symfony/polyfill-mbstring (v1.29.0)
php-1       |   - Locking symfony/polyfill-php83 (v1.29.0)
php-1       |   - Locking symfony/runtime (v7.0.7)
php-1       |   - Locking symfony/service-contracts (v3.5.0)
php-1       |   - Locking symfony/var-dumper (v7.0.7)
php-1       |   - Locking symfony/var-exporter (v7.0.7)
php-1       | Writing lock file
php-1       | Installing dependencies from lock file (including require-dev)
php-1       | Package operations: 18 installs, 0 updates, 0 removals
php-1       |   - Downloading symfony/runtime (v7.0.7)
php-1       |   - Downloading symfony/flex (v2.4.5)
php-1       |   - Downloading symfony/polyfill-php83 (v1.29.0)
php-1       |   - Downloading symfony/polyfill-mbstring (v1.29.0)
php-1       |   - Downloading symfony/http-foundation (v7.0.7)
php-1       |   - Downloading psr/event-dispatcher (1.0.0)
php-1       |   - Downloading symfony/event-dispatcher-contracts (v3.5.0)
php-1       |   - Downloading symfony/event-dispatcher (v7.0.7)
php-1       |   - Downloading symfony/var-dumper (v7.0.7)
php-1       |   - Downloading psr/log (3.0.0)
php-1       |   - Downloading symfony/error-handler (v7.0.7)
php-1       |   - Downloading symfony/http-kernel (v7.0.7)
php-1       |   - Downloading symfony/var-exporter (v7.0.7)
php-1       |   - Downloading symfony/deprecation-contracts (v3.5.0)
php-1       |   - Downloading psr/container (2.0.2)
php-1       |   - Downloading symfony/service-contracts (v3.5.0)
php-1       |   - Downloading symfony/dependency-injection (v7.0.7)
php-1       |   - Downloading runtime/frankenphp-symfony (0.2.0)
php-1       |   0/18 [>---------------------------]   0%
php-1       |  12/18 [==================>---------]  66%
php-1       |  17/18 [==========================>-]  94%
php-1       |  18/18 [============================] 100%
php-1       |   - Installing symfony/runtime (v7.0.7): Extracting archive
php-1       |   - Installing symfony/flex (v2.4.5): Extracting archive
php-1       |   - Installing symfony/polyfill-php83 (v1.29.0): Extracting archive
php-1       |   - Installing symfony/polyfill-mbstring (v1.29.0): Extracting archive
php-1       |   - Installing symfony/http-foundation (v7.0.7): Extracting archive
php-1       |   - Installing psr/event-dispatcher (1.0.0): Extracting archive
php-1       |   - Installing symfony/event-dispatcher-contracts (v3.5.0): Extracting archive
php-1       |   - Installing symfony/event-dispatcher (v7.0.7): Extracting archive
php-1       |   - Installing symfony/var-dumper (v7.0.7): Extracting archive
php-1       |   - Installing psr/log (3.0.0): Extracting archive
php-1       |   - Installing symfony/error-handler (v7.0.7): Extracting archive
php-1       |   - Installing symfony/http-kernel (v7.0.7): Extracting archive
php-1       |   - Installing symfony/var-exporter (v7.0.7): Extracting archive
php-1       |   - Installing symfony/deprecation-contracts (v3.5.0): Extracting archive
php-1       |   - Installing psr/container (2.0.2): Extracting archive
php-1       |   - Installing symfony/service-contracts (v3.5.0): Extracting archive
php-1       |   - Installing symfony/dependency-injection (v7.0.7): Extracting archive
php-1       |   - Installing runtime/frankenphp-symfony (0.2.0): Extracting archive
php-1       |   0/16 [>---------------------------]   0%
php-1       |  16/16 [============================] 100%
php-1       | Generating autoload files
php-1       | 15 packages you are using are looking for funding.
php-1       | Use the `composer fund` command to find out more!
php-1       |
php-1       | Run composer recipes at any time to see the status of your Symfony recipes.
php-1       |
php-1       | Loading composer repositories with package information
php-1       | Restricting packages listed in "symfony/symfony" to "7.0.*"
php-1       | Updating dependencies
php-1       | Lock file operations: 15 installs, 0 updates, 0 removals
php-1       |   - Locking psr/cache (3.0.0)
php-1       |   - Locking symfony/cache (v7.0.7)
php-1       |   - Locking symfony/cache-contracts (v3.5.0)
php-1       |   - Locking symfony/config (v7.0.7)
php-1       |   - Locking symfony/console (v7.0.7)
php-1       |   - Locking symfony/dotenv (v7.0.7)
php-1       |   - Locking symfony/filesystem (v7.0.7)
php-1       |   - Locking symfony/finder (v7.0.7)
php-1       |   - Locking symfony/framework-bundle (v7.0.7)
php-1       |   - Locking symfony/polyfill-intl-grapheme (v1.29.0)
php-1       |   - Locking symfony/polyfill-intl-normalizer (v1.29.0)
php-1       |   - Locking symfony/process (v7.0.7)
php-1       |   - Locking symfony/routing (v7.0.7)
php-1       |   - Locking symfony/string (v7.0.7)
php-1       |   - Locking symfony/yaml (v7.0.7)
php-1       | Writing lock file
php-1       | Installing dependencies from lock file (including require-dev)
php-1       | Package operations: 15 installs, 0 updates, 0 removals
php-1       |   - Downloading psr/cache (3.0.0)
php-1       |   - Downloading symfony/cache-contracts (v3.5.0)
php-1       |   - Downloading symfony/polyfill-intl-normalizer (v1.29.0)
php-1       |   - Downloading symfony/polyfill-intl-grapheme (v1.29.0)
php-1       |   - Downloading symfony/string (v7.0.7)
php-1       |   - Downloading symfony/console (v7.0.7)
php-1       |   - Downloading symfony/dotenv (v7.0.7)
php-1       |   - Downloading symfony/routing (v7.0.7)
php-1       |   - Downloading symfony/finder (v7.0.7)
php-1       |   - Downloading symfony/process (v7.0.7)
php-1       |   - Downloading symfony/filesystem (v7.0.7)
php-1       |   - Downloading symfony/config (v7.0.7)
php-1       |   - Downloading symfony/cache (v7.0.7)
php-1       |   - Downloading symfony/framework-bundle (v7.0.7)
php-1       |   - Downloading symfony/yaml (v7.0.7)
php-1       |   - Installing psr/cache (3.0.0): Extracting archive
php-1       |   - Installing symfony/cache-contracts (v3.5.0): Extracting archive
php-1       |   - Installing symfony/polyfill-intl-normalizer (v1.29.0): Extracting archive
php-1       |   - Installing symfony/polyfill-intl-grapheme (v1.29.0): Extracting archive
php-1       |   - Installing symfony/string (v7.0.7): Extracting archive
php-1       |   - Installing symfony/console (v7.0.7): Extracting archive
php-1       |   - Installing symfony/dotenv (v7.0.7): Extracting archive
php-1       |   - Installing symfony/routing (v7.0.7): Extracting archive
php-1       |   - Installing symfony/finder (v7.0.7): Extracting archive
php-1       |   - Installing symfony/process (v7.0.7): Extracting archive
php-1       |   - Installing symfony/filesystem (v7.0.7): Extracting archive
php-1       |   - Installing symfony/config (v7.0.7): Extracting archive
php-1       |   - Installing symfony/cache (v7.0.7): Extracting archive
php-1       |   - Installing symfony/framework-bundle (v7.0.7): Extracting archive
php-1       |   - Installing symfony/yaml (v7.0.7): Extracting archive
php-1       | Generating autoload files
php-1       | 29 packages you are using are looking for funding.
php-1       | Use the `composer fund` command to find out more!
php-1       |
php-1       | Symfony operations: 4 recipes (71c14000f4667af1c43b3f034957ff00)
php-1       |   - Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:main
php-1       |   - Configuring symfony/framework-bundle (>=7.0): From github.com/symfony/recipes:main
php-1       |   - Configuring symfony/console (>=5.3): From github.com/symfony/recipes:main
php-1       |   - Configuring symfony/routing (>=7.0): From github.com/symfony/recipes:main
php-1       | Executing script cache:clear [OK]
php-1       | Executing script assets:install public [OK]
php-1       |
php-1       |  What's next?
php-1       |
php-1       |
php-1       | Some files have been created and/or updated to configure your new packages.
php-1       | Please review, edit and commit them: these files are yours.
php-1       |
php-1       |  symfony/framework-bundle  instructions:
php-1       |
php-1       |   * Run your application:
php-1       |     1. Go to the project directory
php-1       |     2. Create your code repository with the git init command
php-1       |     3. Download the Symfony CLI at https://symfony.com/download to install a development web server
php-1       |
php-1       |   * Read the documentation at https://symfony.com/doc
php-1       |
php-1       |
php-1       | No security vulnerability advisories found.
php-1       | No security vulnerability advisories found.
php-1       | Using version ^0.2.0 for runtime/frankenphp-symfony
php-1       | {"level":"info","ts":1715134185.6522853,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":""}
php-1       | {"level":"warn","ts":1715134185.655862,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":14}
php-1       | {"level":"info","ts":1715134185.6609757,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
php-1       | {"level":"info","ts":1715134185.6615005,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
php-1       | {"level":"info","ts":1715134185.6616712,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
php-1       | {"level":"warn","ts":1715134185.6618629,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv1","http_port":80}
php-1       | {"level":"info","ts":1715134185.662269,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000404500"}
php-1       | {"level":"info","ts":1715134185.6640227,"logger":"http","msg":"enabling HTTP/3 listener","addr":":443"}
php-1       | {"level":"info","ts":1715134185.6643577,"msg":"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details."}
php-1       | {"level":"info","ts":1715134185.6647031,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
php-1       | {"level":"info","ts":1715134185.6649504,"logger":"http.log","msg":"server running","name":"srv1","protocols":["h1","h2","h3"]}
php-1       | {"level":"info","ts":1715134185.6650584,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["mondomaine.fr"]}
php-1       | {"level":"info","ts":1715134185.6666362,"msg":"FrankenPHP started 🐘","php_version":"8.3.6"}
php-1       | {"level":"info","ts":1715134185.6673129,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
php-1       | {"level":"info","ts":1715134185.6673753,"msg":"serving initial configuration"}
php-1       | {"level":"warn","ts":1715134185.6687148,"logger":"tls","msg":"storage cleaning happened too recently; skipping for now","storage":"FileStorage:/data/caddy","instance":"172aed94-5c5b-49f9-abb3-bbbb7039a4e3","try_again":1715220585.6687124,"try_again_in":86399.999999466}
php-1       | {"level":"info","ts":1715134185.668988,"logger":"tls","msg":"finished cleaning storage units"}
php-1       | {"level":"info","ts":1715134185.6697884,"logger":"watcher","msg":"watching config file for changes","config_file":"/etc/caddy/Caddyfile"}
```

When doing `docker ps` database is **unhealthy**
```
CONTAINER ID   IMAGE                COMMAND                  CREATED         STATUS                     PORTS                                                                                                                       NAMES
becaf01e6d1c   app-php              "docker-entrypoint f…"   3 minutes ago   Up 3 minutes (healthy)     0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:443->443/udp, :::443->443/udp, 2019/tcp   mondomaine-php-1
d59f37f7bc7c   postgres:16-alpine   "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes (unhealthy)   5432/tcp                                                                                                                    mondomaine-database-1
```

Here are my files : 
### compose.yaml
```yml
services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^${SERVER_NAME:-example\.com|localhost}|php$$}
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready -U ${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  caddy_data:
  caddy_config:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
```

### compose.override.yaml
```yaml
# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /app/vendor
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      #CADDY_GLOBAL_OPTIONS: debug
      #FRANKENPHP_CONFIG: "worker ./public/index.php"
      #APP_RUNTIME: "Runtime\\FrankenPhpSymfony\\Runtime"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
```

### compose.prod.yaml
```yaml
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
```

### .env
```env
# In all environments, the following files are loaded if they exist,
# the latter taking precedence over the former:
#
#  * .env                contains default values for the environment variables needed by the app
#  * .env.local          uncommitted file with local overrides
#  * .env.$APP_ENV       committed environment-specific defaults
#  * .env.$APP_ENV.local uncommitted environment-specific overrides
#
# Real environment variables win over .env files.
#
# DO NOT DEFINE PRODUCTION SECRETS IN THIS FILE NOR IN ANY OTHER COMMITTED FILES.
# https://symfony.com/doc/current/configuration/secrets.html
#
# Run "composer dump-env prod" to compile .env files for production use (requires symfony/flex >=1.2).
# https://symfony.com/doc/current/best_practices.html#use-environment-variables-for-infrastructure-configuration

###> symfony/framework-bundle ###
APP_ENV=dev
APP_SECRET=2ba84f6b20cca2880319d2abe9f99614
###< symfony/framework-bundle ###

###> doctrine/doctrine-bundle ###
# Format described at https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
# IMPORTANT: You MUST configure your server version, either here or in config/packages/doctrine.yaml
#
# DATABASE_URL="sqlite:///%kernel.project_dir%/var/data.db"
# DATABASE_URL="mysql://app:!ChangeMe!@127.0.0.1:3306/app?serverVersion=8.0.32&charset=utf8mb4"
# DATABASE_URL="mysql://app:!ChangeMe!@127.0.0.1:3306/app?serverVersion=10.11.2-MariaDB&charset=utf8mb4"
DATABASE_URL="postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8"
###< doctrine/doctrine-bundle ###

###> symfony/messenger ###
# Choose one of the transports below
# MESSENGER_TRANSPORT_DSN=amqp://guest:guest@localhost:5672/%2f/messages
# MESSENGER_TRANSPORT_DSN=redis://localhost:6379/messages
MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0
###< symfony/messenger ###

###> symfony/mailer ###
MAILER_DSN=smtp://mailer:1025
###< symfony/mailer ###

CONTACT_EMAIL=contact@mondomaine.fr
```

### .env.prod
```env
# In all environments, the following files are loaded if they exist,
# the latter taking precedence over the former:
#
#  * .env                contains default values for the environment variables needed by the app
#  * .env.local          uncommitted file with local overrides
#  * .env.$APP_ENV       committed environment-specific defaults
#  * .env.$APP_ENV.local uncommitted environment-specific overrides
#
# Real environment variables win over .env files.
#
# DO NOT DEFINE PRODUCTION SECRETS IN THIS FILE NOR IN ANY OTHER COMMITTED FILES.
# https://symfony.com/doc/current/configuration/secrets.html
#
# Run "composer dump-env prod" to compile .env files for production use (requires symfony/flex >=1.2).
# https://symfony.com/doc/current/best_practices.html#use-environment-variables-for-infrastructure-configuration

###> symfony/framework-bundle ###
APP_ENV=prod
###< symfony/framework-bundle ###

###> doctrine/doctrine-bundle ###
# Format described at https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
# IMPORTANT: You MUST configure your server version, either here or in config/packages/doctrine.yaml
#
# DATABASE_URL="sqlite:///%kernel.project_dir%/var/data.db"
# DATABASE_URL="mysql://app:!ChangeMe!@127.0.0.1:3306/app?serverVersion=8.0.32&charset=utf8mb4"
# DATABASE_URL="mysql://app:!ChangeMe!@127.0.0.1:3306/app?serverVersion=10.11.2-MariaDB&charset=utf8mb4"
DATABASE_URL="postgresql://app:!ChangeMe!@database:5432/app?serverVersion=16&charset=utf8"
###< doctrine/doctrine-bundle ###

###> symfony/messenger ###
# Choose one of the transports below
# MESSENGER_TRANSPORT_DSN=amqp://guest:guest@localhost:5672/%2f/messages
# MESSENGER_TRANSPORT_DSN=redis://localhost:6379/messages
MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0
###< symfony/messenger ###

###> symfony/mailer ###
MAILER_DSN=smtp://mailer:1025
###< symfony/mailer ###

CONTACT_EMAIL=contact@mondomaine.fr
```

### CI.yml
```yaml
name: Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      APP_SECRET:
        description: 'A token passed from the caller workflow'
        required: true
      CADDY_MERCURE_JWT_SECRET:
        description: 'A token passed from the caller workflow'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull latest code changes
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ vars.SSH_PORT }} ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} "if [ ! -d ${{ vars.DEPLOY_DIRECTORY_PROD }}/.git ]; then git clone -b main https://oauth2:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} ${{ vars.DEPLOY_DIRECTORY_PROD }}; fi && cd ${{ vars.DEPLOY_DIRECTORY_PROD }} && git checkout main && git pull origin main"

      - name: Build docker images
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ vars.SSH_PORT }} ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} "cd ${{ vars.DEPLOY_DIRECTORY_PROD }} && docker compose build --no-cache"

      - name: Stop old containers
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ vars.SSH_PORT }} ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} "cd ${{ vars.DEPLOY_DIRECTORY_PROD }} && docker compose down"

      - name: Start containers
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ vars.SSH_PORT }} ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} "cd ${{ vars.DEPLOY_DIRECTORY_PROD }} && SERVER_NAME='${{ vars.PROD_SERVER_NAME }}' APP_SECRET='${{ secrets.APP_SECRET }}' CADDY_MERCURE_JWT_SECRET='${{ secrets.CADDY_MERCURE_JWT_SECRET }}' docker compose -f compose.yaml -f compose.prod.yaml up -d --wait --force-recreate"
      - name: Build assets
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ vars.SSH_PORT }} ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} "cd ${{ vars.DEPLOY_DIRECTORY_PROD }} && docker run --rm -v ./:/app -w /app node:lts-alpine sh -c 'yarn install; yarn build' && rm -rf './node_modules/'"
          
```

As you can see, i'm using variables and secrets provided in github

Does I miss something in the configuration ?

Thanks a lot to took time to read and answer

Stoufiler
