### ISSUE TITLE
Docker escape error 

### ISSUE THREAD

**Issue by Guteres007** [dunglas/symfony-docker#635]
I started first time
`docker compose up`

After start a get  immediately error:
```                                                       
invalid interpolation format for services.php.environment.TRUSTED_HOSTS.
You may need to escape any $ with another $.
^${SERVER_NAME:-example\.com|localhost
```

I fixed it, but I think, it should be fine for the first run.

Fixed with this: 

``` yaml 
TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^$${SERVER_NAME:-example\\.com|localhost}|php$$}
DATABASE_URL: postgresql://$${POSTGRES_USER:-app}:$${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/$${POSTGRES_DB:-app}?serverVersion=$${POSTGRES_VERSION:-15}&charset=$${POSTGRES_CHARSET:-utf8}
MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://$${SERVER_NAME:-localhost}/.well-known/mercure}
```
