### ISSUE TITLE
Need help for production build

### ISSUE THREAD

**Issue by xdesbieys** [dunglas/symfony-docker#65]
Hello everybody

I'm trying to understand how can I use this project in production and I would like to have a single Dockerfile for dev and prod.

I see that there is a possibility:
```yaml
volumes:
    # Comment out the next line in production
    - ./:/srv/app:rw,cached
```
So if I comment this line, I understand that all my app is copied in the image during the build :
```dockerfile
COPY . .
```
`composer install` for dev is run in `php/docker-entrypoint.sh` when php container is up :
```bash
if [ "$APP_ENV" != 'prod' ]; then
    composer install --prefer-dist --no-progress --no-suggest --no-interaction
fi
```
In `.dockerignore` there is `.env*`, all environment files are ignored in copy.
I have create a `docker-compose.prod.yml` based on the original `docker-compose.yml` :
```yaml
version: "3.4"

services:
    mariadb:
        build:
            context: .
            target: symfony_mariadb
        volumes:
            - mariadb:/var/lib/mysql

    php:
        build:
            context: .
            target: symfony_php
            args:
                SYMFONY_VERSION: ${SYMFONY_VERSION:-4.4.*}
                STABILITY: ${STABILITY:-stable}
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s
        environment:
            - APP_ENV=prod
            - SYMFONY_VERSION

    nginx:
        build:
            context: .
            target: symfony_nginx
        ports:
            - "80:8080"
        depends_on:
            - php

volumes:
    mariadb:
        driver: local
```
I have putted:
```yaml
environment:
    - APP_ENV=prod
```

Is this the right way do to this or I'm doing it wrong ?

Where do I put the `composer install` for production ?
During the build after `COPY . .` ? But `cache:clear` from the composer.json failed, there are no environment vars.
How do I declare environment vars ?

Thanks.
