### ISSUE TITLE
Production issue: environment variable not found "MAILER_DSN"

### ISSUE THREAD

**Issue by gremo** [dunglas/symfony-docker#667]
I've the following error when building for production:

```txt
1.185 Generated optimized autoload files (authoritative) containing 4185 classes
1.189 + composer dump-env prod
1.257 Successfully dumped .env files in .env.local.php
1.260 + bin/console cache:clear
1.451
1.452 In EnvVarProcessor.php line 221:
1.452
1.452   Environment variable not found: "MAILER_DSN".
1.452
1.452
```

The issue occurs **only when using the following monolog configuration**:

```yaml
when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: grouped
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            grouped:
                type: group
                members: [streamed, deduplicated]
            streamed:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
            deduplicated:
                type: deduplication
                handler: symfony_mailer
            symfony_mailer:
                type: symfony_mailer
                from_email: 'no-reply@example.com'
                to_email: 'ops@example.com'
                subject: 'An Error Occurred! %%message%%'
                level: debug
                formatter: monolog.formatter.html
                content_type: text/html
```

I've double checked `.env.local.php` generated by composer dump-env prod and it contains the `MAILER_DSN` variable. Any help is much appreciated!
