### ISSUE TITLE
Redirects and HTTPs

### ISSUE THREAD

**Issue by thePanz** [dunglas/symfony-docker#68]
When configuring a route with a redirect like:
```yaml
# routes/routes.yaml
legacy_homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: '/home'
```

The redirect it always using the `http` schema, if the `TRUSTED_PROXIES` environment is not set. When setting it, the redirect works perfectly.

This behavior should be mentioned in the readme, wdty?
