### ISSUE TITLE
App behind Nginx SSL proxy

### ISSUE THREAD

**Issue by prugala** [dunglas/symfony-docker#700]
Hi

Im trying to run app behind nginx proxy but doesn't work.

My nginx site configuration:
```
server {
  server_name mywebsite.com;
  location / {
     proxy_pass http://127.0.0.1:8081;
     proxy_set_header Host $host;
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mywebsite.comfullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mywebsite.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = mywebsite.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


  server_name mywebsite.com;
    listen 80;
    return 404; # managed by Certbot


}
```

compose.prod.yaml:
```
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    env_file:
      - .env
    volumes:
      - ./config/jwt:/app/config/jwt
    ports:
      # HTTP
      - target: 80
        published: 8081
        protocol: tcp
```

When I use directly `ip:8081` app works, same if I change my nginx to work on 80 without SSL `https://mydomain.com` app works.
When I use Nginx with SSL when I'm trying to open app with URL `https://mydomain.com` have the error: `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`
