### ISSUE TITLE
Could `CADDY_MERCURE_JWT_SECRET` be a runtime env var?

### ISSUE THREAD

**Issue by norkunas** [dunglas/symfony-docker#702]
I build the end docker image in the github actions. It is working properly, but I was disabled mercure.
Now after enabling it, i get:
```
php-1  | Error: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 2: loading handler modules: position 1: loading module 'mercure': provision http.handlers.mercure: a JWT key or the URL of a JWK Set for publishers must be provided
```

But I always provide it:
```
SERVER_NAME=... \
CADDY_MERCURE_JWT_SECRET=... \
docker compose ... up -d
```

For some reason I was getting this even before enabling mercure: `WARN[0000] The "CADDY_MERCURE_JWT_SECRET" variable is not set. Defaulting to a blank string.`

Now I have tried to add `ARG CADDY_MERCURE_JWT_SECRET` and `ENV CADDY_MERCURE_JWT_SECRET=$CADDY_MERCURE_JWT_SECRET` to `Dockerfile` and then to the github action (set also the secret for repo):
```
          build-args: |
            CADDY_MERCURE_JWT_SECRET=${{ secrets.CADDY_MERCURE_JWT_SECRET }}
```
but that didn't help.

**Comment by 7-zete-7** [comment]
Hi @norkunas!

This warning (within this project and for this environment variable) can be ignored when building a container. It is intended only for running the container.
Also, you should not pass secrets as arguments for the build, since the arguments are stored as open values ​​in the image build metadata (see https://docs.docker.com/reference/dockerfile/#arg).

Can you show your Caddyfile (how exactly mercure was disabled)?

**Comment by norkunas** [comment]
> Hi @norkunas!

Hey!

> This warning (within this project and for this environment variable) can be ignored when building a container. It is intended only for running the container.

That bothers me everytime because I get the same log maybe 5-10 times per docker command..

> Also, you should not pass secrets as arguments for the build, since the arguments are stored as open values ​​in the image build metadata (see https://docs.docker.com/reference/dockerfile/#arg).

I know, but was just trying things to make it work..

> Can you show your Caddyfile (how exactly mercure was disabled)?

I just commented the mercure part totally. Is there another way?

**Comment by 7-zete-7** [comment]
> That bothers me everytime because I get the same log maybe 5-10 times per docker command..

To avoid these warnings, you can, for example, set some placeholder as the value of this environment variable during the build steps. For example:
```shell
CADDY_MERCURE_JWT_SECRET=foobar docker compose ... build ...
```
This environment variable value will not be used during the build, it will only eliminate warnings.

> I just commented the mercure part totally.

In my experience, disabling mercure by simply commenting out its configuration won't work. Mercure is connected in a different place. In the Caddyfile of this project, only its configuration is performed. And without configuring, mercure does not receive the parameters necessary for its operation, generating this error.

If this is useful: in my projects, I disabled mercure by disabling access to it and changing its transport to `local://local` (to disable storing history, see https://mercure.rocks/docs/hub/config#directives).

I myself wondered how to correctly disable mercure via configuration. So far, I have only been able to figure out that mercure must be excluded from the FrankenPHP/Caddy build to disable it.

**Comment by norkunas** [comment]
> I disabled mercure by disabling access to it and changing its transport to local://local

Thanks, good to know.
But the point that I came up to the point where I need to use mercure in my project.
So the problem is that it still doesn't use my given `CADDY_MERCURE_JWT_SECRET` and gives the warning :disappointed:

**Comment by 7-zete-7** [comment]
> So the problem is that it still doesn't use my given `CADDY_MERCURE_JWT_SECRET` and gives the warning 😞

To clarify:
- `Error: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 2: loading handler modules: position 1: loading module 'mercure': provision http.handlers.mercure: a JWT key or the URL of a JWK Set for publishers must be provided` — an error in an already running FrankenPHP/Caddy container due to the lack of mercure configuration.
- `WARN[0000] The "CADDY_MERCURE_JWT_SECRET" variable is not set. Defaulting to a blank string.` — a warning when running Docker Compose about the environment variable required for the current compose.yaml files not being passed. No containers or images are affected by this warning. This warning occurs when reading the Docker Compose configuration (the same warning can be obtained by running `docker compose ... config`).

To avoid getting the warning during the build, you can simply use a placeholder as the value of this environment variable.

If this warning appears when running the project, it is likely that this environment variable is not set.

Are you currently getting this warning during build or run?

**Comment by norkunas** [comment]
I'm getting the warning during the run.

My compose.prod.yaml contains:
```yaml
environment:
    CADDY_MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}
    MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
```

**Comment by 7-zete-7** [comment]
@norkunas, Thanks for the information about the environment variable configuration in your compose.yaml file.

What command do you use to run?
Or which GitHub job is being launched?

**Comment by norkunas** [comment]
My build action (it does not give any warning about CADDY_MERCURE_JWT_SECRET):
```yaml
jobs;
  docker:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          target: frankenphp_prod
          push: true
```

And the command which I run in server (which I've provided in my opening comment):
```
SERVER_NAME=... \
CADDY_MERCURE_JWT_SECRET=... \
docker compose -f compose.yaml -f compose.prod.yaml up -d
```
