### ISSUE TITLE
Production deployment issues - restarting 

### ISSUE THREAD

**Issue by mcwnuq** [dunglas/symfony-docker#708]
I've setup my symfony (6.4) app with [this](https://github.com/dunglas/symfony-docker/blob/main/docs/production.md) on my own server.
compose.yaml:
```
services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|php$$
    volumes:
      - caddy_data:/data
      - caddy_config:/config
  database:
    image: mysql:${MYSQL_VERSION:-8}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_ROOT_PASSWORD: "true"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-x}
      MYSQL_USER: ${MYSQL_USER:-app}
    volumes:
      - database_data:/var/lib/mysql:rw

volumes:
  caddy_data:
  caddy_config:
  database_data:
```
compose.prod.yaml:
```
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      APP_RUNTIME: Runtime\\FrankenPhpSymfony\\Runtime
    env_file:
      - .env.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.x.rule=Host(`x`)"
      - "traefik.http.routers.x.entrypoints=websecure"
      - "traefik.http.routers.x.tls.certresolver=myresolver"
```

When i start app ( docker compose -f compose.yaml -f compose.prod.yaml up ) i get this:
```
php-1       | The database is now ready and reachable
php-1       | PHP app ready!
php-1       | {"level":"info","ts":1733743942.7789645,"msg":"using config from file","file":"/etc/caddy/Caddyfile"}
php-1       | {"level":"info","ts":1733743942.7809503,"msg":"adapted config to JSON","adapter":"caddyfile"}
php-1       | {"level":"warn","ts":1733743942.7809672,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":9}
php-1       | {"level":"info","ts":1733743942.7827852,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
php-1       | {"level":"info","ts":1733743942.783077,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
php-1       | {"level":"info","ts":1733743942.7830968,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
php-1       | {"level":"warn","ts":1733743942.7831283,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv1","http_port":80}
php-1       | {"level":"info","ts":1733743942.7845228,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0005eee80"}
php-1       | {"level":"info","ts":1733743943.4812634,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.484627,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.4846487,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.4847276,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.485653,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.48579,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.490562,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.4928446,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.4929755,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.4956768,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.498099,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.498099,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.484787,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5015097,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.503732,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.4909956,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5043988,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5072887,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5094068,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.4910636,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5113285,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5139182,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5155993,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5162117,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5182848,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.520284,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5223591,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5240908,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.498128,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.527135,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5284286,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5287771,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5299015,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5342484,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5343645,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5038154,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5342486,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5399349,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5240788,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5342786,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5094137,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5452058,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5453074,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5453331,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5478082,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5504057,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5511117,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5529249,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5531366,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.555602,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5570185,"msg":"restarting","worker":"/app/public/index.php"}
php-1       | {"level":"info","ts":1733743943.5590088,"msg":"restarting","worker":"/app/public/index.php"}
```
