### ISSUE TITLE
The repository at "/app" does not have the correct ownership and git refuses to use it

### ISSUE THREAD

**Issue by norkunas** [dunglas/symfony-docker#744]
```
 The repository at "/app" does not have the correct ownership and git refuses to use it:
php-1  | 
php-1  | fatal: detected dubious ownership in repository at '/app'
php-1  | To add an exception for this directory, call:
php-1  | 
php-1  | 	git config --global --add safe.directory /app
```

I get this a lot, it works even without running the suggested line, but this is warned after each docker down and up run's, so it annoys.
How do you resolve this?

**Comment by 7-zete-7** [comment]
Hi @norkunas!

This message occurs during Composer execution. There is already an issue about this message. See https://github.com/composer/composer/issues/12221.

**Comment by norkunas** [comment]
Hi :)

So it just should be ignored then..

**Comment by maxhelias** [comment]
Thanks @7-zete-7 for the link. 
It looks like the issue is on the side of composer so yes just ignore it for now

**Comment by creativehubspace** [comment]
```
services:
  php:
      command: >
      sh -c "git config --global --add safe.directory /app && frankenphp run --config /etc/caddy/Caddyfile"
```

As a workaround, I have setup this command in my compose.override.yaml for my dev env.
